version: "3"
services:
  mongo:
    container_name: craft-mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
    depends_on:
      - mongo
    ports:
      - "8888:8081"
