version: "3"
services:
  mongo:
    container_name: craft-mongo
    image: mongo:4.2.8
    environment:
      - BACK_HOST_URL={BACK_HOST_URL}
      - BACK_HOST_PORT={BACK_HOST_PORT}
    ports:
      - "27017:27017"
    volumes:
      - .db-data:/data/db
    networks:
      - backend

  mongo-express:
    container_name: craft-mongo-express
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
    depends_on:
      - mongo
    ports:
      - "8888:8081"
    networks:
      - backend

  back:
    container_name: craft-back
    image: "node:13"
    working_dir: /home/node/app
    volumes:
      - ./back:/home/node/app
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_API_KEY}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    ports:
      - "1337:1337"
    command: "yarn dev"
    depends_on:
      - "mongo"
    networks:
      - backend
      - frontend

  front:
    container_name: craft-front
    image: "node:13"
    working_dir: /home/node/app
    volumes:
      - ./front:/home/node/app
    environment:
      - BACKEND_API_ENDPOINT=${BACKEND_API_ENDPOINT}
      - BACKEND_SERVER_ENDPOINT=${BACKEND_SERVER_ENDPOINT}
      - BACKEND_GRAPHQL_ENDPOINT=${BACKEND_GRAPHQL_ENDPOINT}
      - FRONT_HOST_URL=${FRONT_HOST_URL}
      - FRONT_HOST_PORT=${FRONT_HOST_PORT}
      - STRIPE_API_KEY=${STRIPE_PUBLISHABLE_API_KEY}
      - SIRET_API_ENDPOINT=${SIRET_API_ENDPOINT}
    ports:
      - ${FRONT_HOST_PORT}:${FRONT_HOST_PORT}
    command: "yarn dev"
    depends_on:
      - "back"
    networks:
      - frontend

networks:
  frontend:
  backend:
