<template>
  <el-select id="dest_country" v-model="country" @change="onChange" placeholder="Country" filterable>
    <el-option value="AF" label="Afghanistan">Afghanistan</el-option>
    <el-option value="AX">Åland Islands</el-option>
    <el-option value="AL">Albania</el-option>
    <el-option value="DZ">Algeria</el-option>
    <el-option value="AS">American Samoa</el-option>
    <el-option value="AD">Andorra</el-option>
    <el-option value="AO">Angola</el-option>
    <el-option value="AI">Anguilla</el-option>
    <el-option value="AQ">Antarctica</el-option>
    <el-option value="AG">Antigua and Barbuda</el-option>
    <el-option value="AR">Argentina</el-option>
    <el-option value="AM">Armenia</el-option>
    <el-option value="AW">Aruba</el-option>
    <el-option value="AU">Australia</el-option>
    <el-option value="AT">Austria</el-option>
    <el-option value="AZ">Azerbaijan</el-option>
    <el-option value="BS">Bahamas</el-option>
    <el-option value="BH">Bahrain</el-option>
    <el-option value="BD">Bangladesh</el-option>
    <el-option value="BB">Barbados</el-option>
    <el-option value="BY">Belarus</el-option>
    <el-option value="BE">Belgium</el-option>
    <el-option value="BZ">Belize</el-option>
    <el-option value="BJ">Benin</el-option>
    <el-option value="BM">Bermuda</el-option>
    <el-option value="BT">Bhutan</el-option>
    <el-option value="BO">Bolivia, Plurinational State of</el-option>
    <el-option value="BQ">Bonaire, Sint Eustatius and Saba</el-option>
    <el-option value="BA">Bosnia and Herzegovina</el-option>
    <el-option value="BW">Botswana</el-option>
    <el-option value="BV">Bouvet Island</el-option>
    <el-option value="BR">Brazil</el-option>
    <el-option value="IO">British Indian Ocean Territory</el-option>
    <el-option value="BN">Brunei Darussalam</el-option>
    <el-option value="BG">Bulgaria</el-option>
    <el-option value="BF">Burkina Faso</el-option>
    <el-option value="BI">Burundi</el-option>
    <el-option value="KH">Cambodia</el-option>
    <el-option value="CM">Cameroon</el-option>
    <el-option value="CA">Canada</el-option>
    <el-option value="CV">Cape Verde</el-option>
    <el-option value="KY">Cayman Islands</el-option>
    <el-option value="CF">Central African Republic</el-option>
    <el-option value="TD">Chad</el-option>
    <el-option value="CL">Chile</el-option>
    <el-option value="CN">China</el-option>
    <el-option value="CX">Christmas Island</el-option>
    <el-option value="CC">Cocos (Keeling) Islands</el-option>
    <el-option value="CO">Colombia</el-option>
    <el-option value="KM">Comoros</el-option>
    <el-option value="CG">Congo</el-option>
    <el-option value="CD">Congo, the Democratic Republic of the</el-option>
    <el-option value="CK">Cook Islands</el-option>
    <el-option value="CR">Costa Rica</el-option>
    <el-option value="CI">Côte d'Ivoire</el-option>
    <el-option value="HR">Croatia</el-option>
    <el-option value="CU">Cuba</el-option>
    <el-option value="CW">Curaçao</el-option>
    <el-option value="CY">Cyprus</el-option>
    <el-option value="CZ">Czech Republic</el-option>
    <el-option value="DK">Denmark</el-option>
    <el-option value="DJ">Djibouti</el-option>
    <el-option value="DM">Dominica</el-option>
    <el-option value="DO">Dominican Republic</el-option>
    <el-option value="EC">Ecuador</el-option>
    <el-option value="EG">Egypt</el-option>
    <el-option value="SV">El Salvador</el-option>
    <el-option value="GQ">Equatorial Guinea</el-option>
    <el-option value="ER">Eritrea</el-option>
    <el-option value="EE">Estonia</el-option>
    <el-option value="ET">Ethiopia</el-option>
    <el-option value="FK">Falkland Islands (Malvinas)</el-option>
    <el-option value="FO">Faroe Islands</el-option>
    <el-option value="FJ">Fiji</el-option>
    <el-option value="FI">Finland</el-option>
    <el-option value="FR">France</el-option>
    <el-option value="GF">French Guiana</el-option>
    <el-option value="PF">French Polynesia</el-option>
    <el-option value="TF">French Southern Territories</el-option>
    <el-option value="GA">Gabon</el-option>
    <el-option value="GM">Gambia</el-option>
    <el-option value="GE">Georgia</el-option>
    <el-option value="DE">Germany</el-option>
    <el-option value="GH">Ghana</el-option>
    <el-option value="GI">Gibraltar</el-option>
    <el-option value="GR">Greece</el-option>
    <el-option value="GL">Greenland</el-option>
    <el-option value="GD">Grenada</el-option>
    <el-option value="GP">Guadeloupe</el-option>
    <el-option value="GU">Guam</el-option>
    <el-option value="GT">Guatemala</el-option>
    <el-option value="GG">Guernsey</el-option>
    <el-option value="GN">Guinea</el-option>
    <el-option value="GW">Guinea-Bissau</el-option>
    <el-option value="GY">Guyana</el-option>
    <el-option value="HT">Haiti</el-option>
    <el-option value="HM">Heard Island and McDonald Islands</el-option>
    <el-option value="VA">Holy See (Vatican City State)</el-option>
    <el-option value="HN">Honduras</el-option>
    <el-option value="HK">Hong Kong</el-option>
    <el-option value="HU">Hungary</el-option>
    <el-option value="IS">Iceland</el-option>
    <el-option value="IN">India</el-option>
    <el-option value="ID">Indonesia</el-option>
    <el-option value="IR">Iran, Islamic Republic of</el-option>
    <el-option value="IQ">Iraq</el-option>
    <el-option value="IE">Ireland</el-option>
    <el-option value="IM">Isle of Man</el-option>
    <el-option value="IL">Israel</el-option>
    <el-option value="IT">Italy</el-option>
    <el-option value="JM">Jamaica</el-option>
    <el-option value="JP">Japan</el-option>
    <el-option value="JE">Jersey</el-option>
    <el-option value="JO">Jordan</el-option>
    <el-option value="KZ">Kazakhstan</el-option>
    <el-option value="KE">Kenya</el-option>
    <el-option value="KI">Kiribati</el-option>
    <el-option value="KP">Korea, Democratic People's Republic of</el-option>
    <el-option value="KR">Korea, Republic of</el-option>
    <el-option value="KW">Kuwait</el-option>
    <el-option value="KG">Kyrgyzstan</el-option>
    <el-option value="LA">Lao People's Democratic Republic</el-option>
    <el-option value="LV">Latvia</el-option>
    <el-option value="LB">Lebanon</el-option>
    <el-option value="LS">Lesotho</el-option>
    <el-option value="LR">Liberia</el-option>
    <el-option value="LY">Libya</el-option>
    <el-option value="LI">Liechtenstein</el-option>
    <el-option value="LT">Lithuania</el-option>
    <el-option value="LU">Luxembourg</el-option>
    <el-option value="MO">Macao</el-option>
    <el-option value="MK">Macedonia, the former Yugoslav Republic of</el-option>
    <el-option value="MG">Madagascar</el-option>
    <el-option value="MW">Malawi</el-option>
    <el-option value="MY">Malaysia</el-option>
    <el-option value="MV">Maldives</el-option>
    <el-option value="ML">Mali</el-option>
    <el-option value="MT">Malta</el-option>
    <el-option value="MH">Marshall Islands</el-option>
    <el-option value="MQ">Martinique</el-option>
    <el-option value="MR">Mauritania</el-option>
    <el-option value="MU">Mauritius</el-option>
    <el-option value="YT">Mayotte</el-option>
    <el-option value="MX">Mexico</el-option>
    <el-option value="FM">Micronesia, Federated States of</el-option>
    <el-option value="MD">Moldova, Republic of</el-option>
    <el-option value="MC">Monaco</el-option>
    <el-option value="MN">Mongolia</el-option>
    <el-option value="ME">Montenegro</el-option>
    <el-option value="MS">Montserrat</el-option>
    <el-option value="MA">Morocco</el-option>
    <el-option value="MZ">Mozambique</el-option>
    <el-option value="MM">Myanmar</el-option>
    <el-option value="NA">Namibia</el-option>
    <el-option value="NR">Nauru</el-option>
    <el-option value="NP">Nepal</el-option>
    <el-option value="NL">Netherlands</el-option>
    <el-option value="NC">New Caledonia</el-option>
    <el-option value="NZ">New Zealand</el-option>
    <el-option value="NI">Nicaragua</el-option>
    <el-option value="NE">Niger</el-option>
    <el-option value="NG">Nigeria</el-option>
    <el-option value="NU">Niue</el-option>
    <el-option value="NF">Norfolk Island</el-option>
    <el-option value="MP">Northern Mariana Islands</el-option>
    <el-option value="NO">Norway</el-option>
    <el-option value="OM">Oman</el-option>
    <el-option value="PK">Pakistan</el-option>
    <el-option value="PW">Palau</el-option>
    <el-option value="PS">Palestinian Territory, Occupied</el-option>
    <el-option value="PA">Panama</el-option>
    <el-option value="PG">Papua New Guinea</el-option>
    <el-option value="PY">Paraguay</el-option>
    <el-option value="PE">Peru</el-option>
    <el-option value="PH">Philippines</el-option>
    <el-option value="PN">Pitcairn</el-option>
    <el-option value="PL">Poland</el-option>
    <el-option value="PT">Portugal</el-option>
    <el-option value="PR">Puerto Rico</el-option>
    <el-option value="QA">Qatar</el-option>
    <el-option value="RE">Réunion</el-option>
    <el-option value="RO">Romania</el-option>
    <el-option value="RU">Russian Federation</el-option>
    <el-option value="RW">Rwanda</el-option>
    <el-option value="BL">Saint Barthélemy</el-option>
    <el-option value="SH">Saint Helena, Ascension and Tristan da Cunha</el-option>
    <el-option value="KN">Saint Kitts and Nevis</el-option>
    <el-option value="LC">Saint Lucia</el-option>
    <el-option value="MF">Saint Martin (French part)</el-option>
    <el-option value="PM">Saint Pierre and Miquelon</el-option>
    <el-option value="VC">Saint Vincent and the Grenadines</el-option>
    <el-option value="WS">Samoa</el-option>
    <el-option value="SM">San Marino</el-option>
    <el-option value="ST">Sao Tome and Principe</el-option>
    <el-option value="SA">Saudi Arabia</el-option>
    <el-option value="SN">Senegal</el-option>
    <el-option value="RS">Serbia</el-option>
    <el-option value="SC">Seychelles</el-option>
    <el-option value="SL">Sierra Leone</el-option>
    <el-option value="SG">Singapore</el-option>
    <el-option value="SX">Sint Maarten (Dutch part)</el-option>
    <el-option value="SK">Slovakia</el-option>
    <el-option value="SI">Slovenia</el-option>
    <el-option value="SB">Solomon Islands</el-option>
    <el-option value="SO">Somalia</el-option>
    <el-option value="ZA">South Africa</el-option>
    <el-option value="GS">South Georgia and the South Sandwich Islands</el-option>
    <el-option value="SS">South Sudan</el-option>
    <el-option value="ES">Spain</el-option>
    <el-option value="LK">Sri Lanka</el-option>
    <el-option value="SD">Sudan</el-option>
    <el-option value="SR">Suriname</el-option>
    <el-option value="SJ">Svalbard and Jan Mayen</el-option>
    <el-option value="SZ">Swaziland</el-option>
    <el-option value="SE">Sweden</el-option>
    <el-option value="CH">Switzerland</el-option>
    <el-option value="SY">Syrian Arab Republic</el-option>
    <el-option value="TW">Taiwan, Province of China</el-option>
    <el-option value="TJ">Tajikistan</el-option>
    <el-option value="TZ">Tanzania, United Republic of</el-option>
    <el-option value="TH">Thailand</el-option>
    <el-option value="TL">Timor-Leste</el-option>
    <el-option value="TG">Togo</el-option>
    <el-option value="TK">Tokelau</el-option>
    <el-option value="TO">Tonga</el-option>
    <el-option value="TT">Trinidad and Tobago</el-option>
    <el-option value="TN">Tunisia</el-option>
    <el-option value="TR">Turkey</el-option>
    <el-option value="TM">Turkmenistan</el-option>
    <el-option value="TC">Turks and Caicos Islands</el-option>
    <el-option value="TV">Tuvalu</el-option>
    <el-option value="UG">Uganda</el-option>
    <el-option value="UA">Ukraine</el-option>
    <el-option value="AE">United Arab Emirates</el-option>
    <el-option value="GB">United Kingdom</el-option>
    <el-option value="US">United States</el-option>
    <el-option value="UM">United States Minor Outlying Islands</el-option>
    <el-option value="UY">Uruguay</el-option>
    <el-option value="UZ">Uzbekistan</el-option>
    <el-option value="VU">Vanuatu</el-option>
    <el-option value="VE">Venezuela, Bolivarian Republic of</el-option>
    <el-option value="VN">Viet Nam</el-option>
    <el-option value="VG">Virgin Islands, British</el-option>
    <el-option value="VI">Virgin Islands, U.S.</el-option>
    <el-option value="WF">Wallis and Futuna</el-option>
    <el-option value="EH">Western Sahara</el-option>
    <el-option value="YE">Yemen</el-option>
    <el-option value="ZM">Zambia</el-option>
    <el-option value="ZW">Zimbabwe</el-option>
  </el-select>
</template>

<script>
export default {
  name: "CountrySelect",
  data: function() {
    return {
      country: null
    }
  },
  methods: {
    onChange: function () {
      this.$emit("change", this.country)
    },
  },
}
</script>
